import type { Metadata } from "next";
import "./globals.css";
import "bootstrap/dist/css/bootstrap.min.css";

import "swiper/css/pagination";
import "swiper/css/navigation";
import "swiper/css";
import "./swiper-custom.css";
import { Toaster } from "react-hot-toast";

export const metadata: Metadata = {
  title: "OLX",
  description: "Generated by Abror",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scrollbar-hide">
      <head>
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
        />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/icon?family=Material+Icons"
        />
      </head>

      <body>
        <Toaster position="top-center" />
        {children}
      </body>
    </html>
  );
}
